Repository gyozatech/noodlog, pull requests merged in 2021-04, with the labels that each got.

#6 ✨ Add automatic changelog
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release-drafter.yml
  .github/workflows/release.yml
Labels: kind/feature

#7 🐛 Fix branch in trigger action
  .github/workflows/release.yml
Labels: type/bugfix

#9 🛠 Add GitHub templates for issue request and bug report
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: type/other

#15 ✨ added func to change logWriter and started implementing some tests
  logger.go
  logger_test.go
Labels: type/feature

#17 ✨ Add Code Coverage with Codecov
  .github/workflows/go.yml
  .github/workflows/release.yml
  .gitignore
  Makefile
  README.md
  codecov.yml
Labels: type/feature

#14 ✨ Added rgb color support and background color
  README.md
  colors.go
  colors_test.go
  constants.go
  log_struct.go
  logger_test.go
Labels: type/feature

#22 📖 Change the description of Bug Report
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: type/doc
